# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7625602d37555363a8f35523e7364c9a5a36a7f0de308510543fc596d9a53bd3ebb2d0a0a653ad9aab3b4156e71fd4a4706d526dc65b8e30fcf3e4453401c56c

test:
  secret_key_base: ad210e9f3c9e1d548edf851724dff071365e8f34288b042d72baac2051f151e4d98c6e4331fb236857a9ba6a64af21c362b2f8e1b98020695354c33c259c3b0d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
